version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cia_hackathon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    ports:
      - "8765:8765"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/cia_hackathon
      REDIS_URL: redis://redis:6379
      YOU_API_KEY: ${YOU_API_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8765 --reload

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3456:3456"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8765
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev -- --port 3456

volumes:
  postgres_data:
  redis_data:
