"""fix_final_foreign_key_types

Revision ID: 58b76129bfc7
Revises: 011
Create Date: 2025-10-30 19:09:29.972199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58b76129bfc7'
down_revision = '011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables with dependencies first
    try:
        op.drop_index('ix_playbook_executions_id', table_name='playbook_executions')
        op.drop_table('playbook_executions')
    except:
        pass
    try:
        op.drop_index('ix_user_playbooks_id', table_name='user_playbooks')
        op.drop_table('user_playbooks')
    except:
        pass
    try:
        op.drop_table('security_controls')
    except:
        pass
    try:
        op.drop_index('ix_integration_logs_id', table_name='integration_logs')
        op.drop_table('integration_logs')
    except:
        pass
    try:
        op.drop_index('ix_trend_sparklines_company_name', table_name='trend_sparklines')
        op.drop_index('ix_trend_sparklines_id', table_name='trend_sparklines')
        op.drop_table('trend_sparklines')
    except:
        pass
    # Drop remaining tables with try-catch to handle dependencies
    try:
        op.drop_table('soc2_audit_logs')
    except:
        pass
    try:
        op.drop_index('ix_action_board_items_id', table_name='action_board_items')
        op.drop_table('action_board_items')
    except:
        pass
    try:
        op.drop_index('ix_playbook_templates_id', table_name='playbook_templates')
        op.drop_table('playbook_templates')
    except:
        pass
    try:
        op.drop_index('ix_action_boards_id', table_name='action_boards')
        op.drop_table('action_boards')
    except:
        pass
    try:
        op.drop_index('ix_insight_timelines_company_name', table_name='insight_timelines')
        op.drop_index('ix_insight_timelines_id', table_name='insight_timelines')
        op.drop_table('insight_timelines')
    except:
        pass
    try:
        op.drop_index('ix_delta_highlights_id', table_name='delta_highlights')
        op.drop_table('delta_highlights')
    except:
        pass
    try:
        op.drop_index('ix_action_reminders_id', table_name='action_reminders')
        op.drop_table('action_reminders')
    except:
        pass
    try:
        op.drop_index('ix_action_items_id', table_name='action_items')
        op.drop_table('action_items')
    except:
        pass
    try:
        op.drop_index('ix_action_templates_id', table_name='action_templates')
        op.drop_table('action_templates')
    except:
        pass
    try:
        op.drop_index('ix_evidence_badges_id', table_name='evidence_badges')
        op.drop_table('evidence_badges')
    except:
        pass
    try:
        op.drop_index('ix_persona_presets_id', table_name='persona_presets')
        op.drop_table('persona_presets')
    except:
        pass
    try:
        op.drop_index('ix_source_evidence_id', table_name='source_evidence')
        op.drop_table('source_evidence')
    except:
        pass
    op.add_column('audit_logs', sa.Column('details', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('session_id', sa.String(), nullable=True))
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'success',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_audit_action_time', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('idx_audit_ip_time', 'audit_logs', ['ip_address', 'created_at'], unique=False)
    op.create_index('idx_audit_resource_time', 'audit_logs', ['resource_type', 'resource_id', 'created_at'], unique=False)
    op.create_index('idx_audit_user_action_time', 'audit_logs', ['user_id', 'action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint('audit_logs_workspace_id_fkey', 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'workspace_id')
    op.drop_column('audit_logs', 'description')
    op.drop_column('audit_logs', 'new_values')
    op.drop_column('audit_logs', 'old_values')
    op.add_column('integrations', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('integrations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('integrations', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('integrations', sa.Column('developer_id', sa.Integer(), nullable=False))
    op.add_column('integrations', sa.Column('developer_name', sa.String(length=255), nullable=True))
    op.add_column('integrations', sa.Column('developer_email', sa.String(length=255), nullable=True))
    op.add_column('integrations', sa.Column('version', sa.String(length=50), nullable=True))
    op.add_column('integrations', sa.Column('webhook_url', sa.String(length=500), nullable=True))
    op.add_column('integrations', sa.Column('configuration_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('integrations', sa.Column('required_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('integrations', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('integrations', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('integrations', sa.Column('install_count', sa.Integer(), nullable=True))
    op.add_column('integrations', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('integrations', sa.Column('rating_count', sa.Integer(), nullable=True))
    op.add_column('integrations', sa.Column('revenue_share_percent', sa.Float(), nullable=True))
    op.add_column('integrations', sa.Column('monthly_revenue', sa.Float(), nullable=True))
    op.add_column('integrations', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.alter_column('integrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('integrations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'integrations', ['slug'])
    op.drop_constraint('integrations_created_by_fkey', 'integrations', type_='foreignkey')
    op.drop_constraint('integrations_workspace_id_fkey', 'integrations', type_='foreignkey')
    op.create_foreign_key(None, 'integrations', 'users', ['developer_id'], ['id'])
    op.drop_column('integrations', 'total_syncs')
    op.drop_column('integrations', 'config')
    op.drop_column('integrations', 'successful_syncs')
    op.drop_column('integrations', 'credentials')
    op.drop_column('integrations', 'is_verified')
    op.drop_column('integrations', 'created_by')
    op.drop_column('integrations', 'last_error')
    op.drop_column('integrations', 'type')
    op.drop_column('integrations', 'is_active')
    op.drop_column('integrations', 'workspace_id')
    op.drop_column('integrations', 'failed_syncs')
    op.drop_column('integrations', 'last_sync_at')
    op.add_column('users', sa.Column('consent_marketing', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('consent_analytics', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('consent_integrations', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('data_retention_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'data_retention_days')
    op.drop_column('users', 'consent_integrations')
    op.drop_column('users', 'consent_analytics')
    op.drop_column('users', 'consent_marketing')
    op.add_column('integrations', sa.Column('last_sync_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('integrations', sa.Column('failed_syncs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('integrations', sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('integrations', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('integrations', sa.Column('type', postgresql.ENUM('SLACK', 'NOTION', 'SALESFORCE', 'MICROSOFT_TEAMS', 'JIRA', 'WEBHOOK', name='integrationtype'), autoincrement=False, nullable=False))
    op.add_column('integrations', sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('integrations', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('integrations', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('integrations', sa.Column('credentials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('integrations', sa.Column('successful_syncs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('integrations', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('integrations', sa.Column('total_syncs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'integrations', type_='foreignkey')
    op.create_foreign_key('integrations_workspace_id_fkey', 'integrations', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key('integrations_created_by_fkey', 'integrations', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'integrations', type_='unique')
    op.alter_column('integrations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('integrations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('integrations', 'approved_at')
    op.drop_column('integrations', 'monthly_revenue')
    op.drop_column('integrations', 'revenue_share_percent')
    op.drop_column('integrations', 'rating_count')
    op.drop_column('integrations', 'rating')
    op.drop_column('integrations', 'install_count')
    op.drop_column('integrations', 'is_featured')
    op.drop_column('integrations', 'status')
    op.drop_column('integrations', 'required_permissions')
    op.drop_column('integrations', 'configuration_schema')
    op.drop_column('integrations', 'webhook_url')
    op.drop_column('integrations', 'version')
    op.drop_column('integrations', 'developer_email')
    op.drop_column('integrations', 'developer_name')
    op.drop_column('integrations', 'developer_id')
    op.drop_column('integrations', 'category')
    op.drop_column('integrations', 'description')
    op.drop_column('integrations', 'slug')
    op.add_column('audit_logs', sa.Column('old_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('new_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('audit_logs_workspace_id_fkey', 'audit_logs', 'workspaces', ['workspace_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_action_time', table_name='audit_logs')
    op.drop_index('idx_audit_resource_time', table_name='audit_logs')
    op.drop_index('idx_audit_ip_time', table_name='audit_logs')
    op.drop_index('idx_audit_action_time', table_name='audit_logs')
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'success',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('audit_logs', 'session_id')
    op.drop_column('audit_logs', 'details')
    op.create_table('source_evidence',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('badge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('source_tier', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('excerpt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('publish_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('relevance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('credibility_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extracted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('you_api_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['evidence_badges.id'], name='source_evidence_badge_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='source_evidence_pkey')
    )
    op.create_index('ix_source_evidence_id', 'source_evidence', ['id'], unique=False)
    op.create_table('persona_presets',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('persona_presets_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('default_data_slices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('export_templates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('follow_up_tasks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('key_questions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('priority_sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('analysis_depth', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('dashboard_layout', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notification_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='persona_presets_pkey'),
    sa.UniqueConstraint('name', name='persona_presets_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_persona_presets_id', 'persona_presets', ['id'], unique=False)
    op.create_table('evidence_badges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confidence_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('confidence_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('total_sources', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tier_1_sources', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tier_2_sources', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tier_3_sources', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tier_4_sources', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('freshness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('oldest_source_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('newest_source_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_source_age_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cross_validation_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bias_detection_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fact_check_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('top_sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('badge_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('badge_icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('display_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='evidence_badges_pkey')
    )
    op.create_index('ix_evidence_badges_id', 'evidence_badges', ['id'], unique=False)
    op.create_table('action_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('template_actions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('default_assignments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('estimated_timeline', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='action_templates_pkey')
    )
    op.create_index('ix_action_templates_id', 'action_templates', ['id'], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('action_items_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('impact_card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PLANNED', 'IN_PROGRESS', 'DONE', 'CANCELLED', name='actionstatus'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='actionpriority'), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('owner_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('progress_percentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_insight', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evidence_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('success_criteria', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_updates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ai_generated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_modified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['impact_card_id'], ['impact_cards.id'], name='action_items_impact_card_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='action_items_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_action_items_id', 'action_items', ['id'], unique=False)
    op.create_table('action_reminders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reminder_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reminder_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('recurring', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('recurrence_pattern', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['action_item_id'], ['action_items.id'], name='action_reminders_action_item_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='action_reminders_pkey')
    )
    op.create_index('ix_action_reminders_id', 'action_reminders', ['id'], unique=False)
    op.create_table('delta_highlights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timeline_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('highlight_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('importance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('freshness_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('badge_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('badge_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('source_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_dismissed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['timeline_id'], ['insight_timelines.id'], name='delta_highlights_timeline_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='delta_highlights_pkey')
    )
    op.create_index('ix_delta_highlights_id', 'delta_highlights', ['id'], unique=False)
    op.create_table('insight_timelines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('impact_card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('previous_analysis_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('previous_risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('risk_score_delta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('new_stories_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_stories_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_evidence_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('key_changes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fresh_insights', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('trend_shifts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('analysis_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['impact_card_id'], ['impact_cards.id'], name='insight_timelines_impact_card_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='insight_timelines_pkey')
    )
    op.create_index('ix_insight_timelines_id', 'insight_timelines', ['id'], unique=False)
    op.create_index('ix_insight_timelines_company_name', 'insight_timelines', ['company_name'], unique=False)
    op.create_table('action_boards',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('action_boards_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('board_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('columns', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('filters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sort_order', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_shared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('shared_with', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_accessed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='action_boards_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_action_boards_id', 'action_boards', ['id'], unique=False)
    op.create_table('playbook_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('template_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('customization_options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='playbook_templates_pkey')
    )
    op.create_index('ix_playbook_templates_id', 'playbook_templates', ['id'], unique=False)
    op.create_table('action_board_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('column_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('custom_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('custom_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('moved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['action_item_id'], ['action_items.id'], name='action_board_items_action_item_id_fkey'),
    sa.ForeignKeyConstraint(['board_id'], ['action_boards.id'], name='action_board_items_board_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='action_board_items_pkey')
    )
    op.create_index('ix_action_board_items_id', 'action_board_items', ['id'], unique=False)
    op.create_table('soc2_audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='soc2_audit_logs_pkey')
    )
    op.create_table('playbook_executions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_playbook_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_company', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('execution_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('generated_artifacts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('completion_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('completion_percentage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('estimated_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_satisfaction_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_saved_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('execution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("completion_status::text = ANY (ARRAY['in_progress'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])", name='check_completion_status'),
    sa.CheckConstraint('completion_percentage >= 0 AND completion_percentage <= 100', name='check_completion_percentage'),
    sa.ForeignKeyConstraint(['user_playbook_id'], ['user_playbooks.id'], name='playbook_executions_user_playbook_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='playbook_executions_pkey')
    )
    op.create_index('ix_playbook_executions_id', 'playbook_executions', ['id'], unique=False)
    op.create_table('trend_sparklines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data_points', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('time_range', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('trend_direction', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trend_strength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='trend_sparklines_pkey')
    )
    op.create_index('ix_trend_sparklines_id', 'trend_sparklines', ['id'], unique=False)
    op.create_index('ix_trend_sparklines_company_name', 'trend_sparklines', ['company_name'], unique=False)
    op.create_table('user_playbooks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('persona_preset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('custom_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('custom_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_used', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('current_step', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_tasks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['persona_preset_id'], ['persona_presets.id'], name='user_playbooks_persona_preset_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_playbooks_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_playbooks_pkey')
    )
    op.create_index('ix_user_playbooks_id', 'user_playbooks', ['id'], unique=False)
    op.create_table('integration_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('integration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name='integration_logs_integration_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='integration_logs_pkey')
    )
    op.create_index('ix_integration_logs_id', 'integration_logs', ['id'], unique=False)
    op.create_table('security_controls',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('control_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('control_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('control_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('soc2_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('implementation_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evidence_location', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('responsible_party', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('review_frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_tested_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_review_due', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('compliance_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='security_controls_pkey'),
    sa.UniqueConstraint('control_id', name='security_controls_control_id_key')
    )
    # ### end Alembic commands ###